In [1]:
import numpy as np

In [14]:
a = np.array([1,2,4,5,6])

In [15]:
b = np.array((12,4,67))

In [17]:
print(a)
print(a.ndim)

[1 2 4 5 6]
1


In [5]:
print(b)

[12  4 67]


In [6]:
type(a)

numpy.ndarray

In [7]:
type(b)

numpy.ndarray

In [8]:
c = np.array([1,2,3,4,5], dtype='i')

In [9]:
c

array([1, 2, 3, 4, 5], dtype=int32)

In [19]:
a = np.array([[1,2,3], [4,5,6]])

In [20]:
print(a)

[[1 2 3]
 [4 5 6]]


In [21]:
print(a.ndim)

2


In [25]:
a[0,2]

np.int64(3)

In [31]:
B = np.array([[1,2,3, -1],[2,3,4,5]])

In [32]:
B.ndim

2

In [33]:
B 

array([[ 1,  2,  3, -1],
       [ 2,  3,  4,  5]])

In [34]:
type(B)

numpy.ndarray

In [35]:
B.shape

(2, 4)

In [36]:
B.size

8

In [39]:
B.byteswap(1)

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
                        -1],
       [144115188075855872, 216172782113783808, 288230376151711744,
        360287970189639680]])

In [40]:
A = np.arange(10)

In [41]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
type(A)

numpy.ndarray

In [43]:
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
A = np.arange(100)

In [45]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [47]:
A = np.arange(10, 30, 4)

In [48]:
A

array([10, 14, 18, 22, 26])

In [49]:
 A = np.random.permutation(np.arange(10))

In [50]:
A

array([1, 0, 4, 6, 2, 8, 3, 7, 5, 9])

In [51]:
A.reshape(2, 5)

array([[1, 0, 4, 6, 2],
       [8, 3, 7, 5, 9]])

In [58]:
A = np.arange(10)

In [59]:
B = A.reshape(5, 2)

In [60]:
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])